In [4]:
import numpy as np
y_train = [1,1,1,1,0,0,0,0]
y_train = np.eye(2)[y_train]
y_train.reshape(8,1,2)
print(y_train.shape)

(8, 2)


In [5]:
x_train_0 = np.loadtxt('./train_0.csv',dtype=str,delimiter = ',',encoding='utf-8-sig')
x_train_1 = np.loadtxt('./train_1.csv',dtype=str,delimiter = ',',encoding='utf-8-sig')
X_train = np.concatenate((x_train_0,x_train_1),axis=0)

In [10]:
print(x_train_0)

[['1.825100611' '1.732494363' '1.207009485' ... '1.07436249'
  '1.482520177' '0']
 ['0.47962274' '0.479909283' '0.478228537' ... '2.1330555' '2.077465799'
  '0']
 ['1.611745241' '1.029656971' '0.972975857' ... '1.516220192'
  '1.466054555' '0']
 ...
 ['0.935707573' '0.936768504' '0.931069362' ... '2.154993705'
  '2.198735735' '0']
 ['1.11703738' '1.102264627' '1.190754822' ... '1.117057804' '1.11703738'
  '0']
 ['1.155727388' '-0.160614966' '-0.100762855' ... '1.155839765'
  '1.155727388' '0']]


In [8]:
y_train = X_train[0:30000,30]
print(y_train.shape)
y_train = y_train[:,np.newaxis].astype(np.int)
print(y_train.shape)
y_train = np.eye(2)[y_train]
print(y_train.shape)
y_train.reshape(30000,1,2)
print(y_train.shape)


(30000,)
(30000, 1)
(30000, 1, 2)
(30000, 1, 2)


/home/wamdm/anaconda3/envs/pytorch18/lib/python3.7/site-packages/ipykernel_launcher.py:3: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  This is separate from the ipykernel package so we can avoid doing imports until


In [9]:
print(y_train)

[[[1. 0.]]

 [[1. 0.]]

 [[1. 0.]]

 ...

 [[0. 1.]]

 [[0. 1.]]

 [[0. 1.]]]


In [2]:
import tensorflow as tf

In [3]:
tf.keras.layers.GRUCell(
    units, activation='tanh', recurrent_activation='sigmoid',
    use_bias=True, kernel_initializer='glorot_uniform',
    recurrent_initializer='orthogonal',
    bias_initializer='zeros', kernel_regularizer=None,
    recurrent_regularizer=None, bias_regularizer=None, kernel_constraint=None,
    recurrent_constraint=None, bias_constraint=None, dropout=0.0,
    recurrent_dropout=0.0, reset_after=True, **kwargs
)

NameError: name 'units' is not defined

In [4]:
import datetime
curr_time1 = datetime.datetime.now()

In [5]:
curr_time2 = datetime.datetime.now()

In [6]:
print(curr_time1,curr_time2,curr_time2-curr_time1)

2021-06-21 22:43:01.138055 2021-06-21 22:43:03.145706 0:00:02.007651
